/**
 * Jarvis J2 — filler WAVs (latency masking, REVIEW §3.3): pre-rendered Kokoro af_sky
 * acks played the instant a turn starts, covering the ~456 ms warm first-audio of the
 * real reply. Assets are generated by scripts/gen-voice-fillers.mjs and committed;
 * playback routes through the TTS player's master gain so a barge-in ducks fillers too.
 */
import oneMomentUrl from '../assets/voice/filler-one-moment.wav?url'
import onItUrl from '../assets/voice/filler-on-it.wav?url'
import { getTtsPlayer } from './ttsPlayback'

export const FILLER_URLS = {
  'one-moment': oneMomentUrl,
  'on-it': onItUrl
} as const

export type FillerKind = keyof typeof FILLER_URLS

const decoded = new Map<FillerKind, AudioBuffer>()

/**
 * Play a filler immediately (decoded once, cached). Resolves once scheduled; a missing
 * player (no TTS session yet this window) is a silent no-op — fillers are garnish,
 * never load-bearing.
 */
export async function playFiller(kind: FillerKind): Promise<void> {
  const player = getTtsPlayer()
  if (!player) return
  try {
    let buf = decoded.get(kind)
    if (!buf) {
      const res = await fetch(FILLER_URLS[kind])
      buf = await player.graph().ctx.decodeAudioData(await res.arrayBuffer())
      decoded.set(kind, buf)
    }
    player.playBuffer(buf)
  } catch {
    /* asset unreachable / decode failure — skip the garnish */
  }
}
