/**
 * tarArchive units — the ustar fixture below is generated by CPython's stdlib tarfile
 * (USTAR_FORMAT): one directory entry (must be skipped), two regular files, one nested
 * file. Plus the malformed-input contract (overrun throws, never a truncated entry).
 */
import { describe, expect, it } from 'vitest'
import { findTarEntry, readTarEntries } from './tarArchive'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const FIXTURE = readFileSync(join(__dirname, '__fixtures__', 'tar-ustar-sample.tar'))

describe('readTarEntries', () => {
  it('lists regular files only (directory entries skipped), with full paths + bytes', () => {
    const entries = readTarEntries(FIXTURE)
    expect(entries.map((e) => e.name)).toEqual([
      'model-dir/tokens.txt',
      'model-dir/encoder.onnx',
      'model-dir/nested/deep.bin'
    ])
    expect(entries[0].data.toString()).toBe('a 1\nb 2\n')
    expect(entries[1].data.length).toBe(768)
    expect(entries[1].data[0]).toBe(0)
    expect(entries[1].data[255]).toBe(255)
    expect(entries[2].data.toString()).toBe('deep')
  })

  it('findTarEntry matches by basename regardless of the archive root dir', () => {
    const entries = readTarEntries(FIXTURE)
    expect(findTarEntry(entries, 'tokens.txt')?.name).toBe('model-dir/tokens.txt')
    expect(findTarEntry(entries, 'deep.bin')?.data.toString()).toBe('deep')
    expect(findTarEntry(entries, 'absent.onnx')).toBeUndefined()
  })

  it('an entry overrunning the buffer throws (truncated download, not a partial file)', () => {
    // Cut inside encoder.onnx's data run: its header (at 1536) parses, the 768-byte
    // payload doesn't fit — the guard must throw rather than emit a short file.
    expect(() => readTarEntries(FIXTURE.subarray(0, 2148))).toThrow(/overruns/)
  })

  it('an empty buffer yields no entries', () => {
    expect(readTarEntries(Buffer.alloc(0))).toEqual([])
    expect(readTarEntries(Buffer.alloc(1024))).toEqual([]) // two zero blocks = EOF
  })
})

describe('long names (the real k2-fsa archives exceed the 100-char name field)', () => {
  const LONG =
    'a-very-long-model-directory-name-that-mirrors-the-kws-release-layout-2024/encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx'

  it('GNU "L" longname entries resolve to the full path (the live J5 dev-check bug)', () => {
    const entries = readTarEntries(
      readFileSync(join(__dirname, '__fixtures__', 'tar-gnu-longname.tar'))
    )
    expect(entries.map((e) => e.name)).toContain(LONG)
    expect(
      findTarEntry(entries, 'encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx')?.data
    ).toEqual(Buffer.from('LONGNAME-ENCODER'))
    expect(findTarEntry(entries, 'tokens.txt')?.data.toString()).toBe('a 1\n')
  })

  it('pax "x" path= records resolve to the full path', () => {
    const entries = readTarEntries(
      readFileSync(join(__dirname, '__fixtures__', 'tar-pax-longname.tar'))
    )
    expect(entries.map((e) => e.name)).toContain(LONG)
    expect(
      findTarEntry(entries, 'encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx')?.data.toString()
    ).toBe('LONGNAME-ENCODER')
  })
})
